apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  labels:
    app: grafana
  name: grafana-data-source
  namespace: grafana
spec:
  datasources:
    - basicAuthUser: internal
      access: proxy
      editable: true
      secureJsonData:
        httpHeaderValue1: 'Bearer '
      name: Prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      basicAuth: false
      isDefault: true
      version: 1
      type: prometheus
  name: grafana-data-source.yaml