apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  config:
    security:
      admin_user: admin 
      admin_password: ocp123
  #dataStorage:
  #  accessModes:
  #    - ReadWriteOnce
  #  class: gp2
  #  size: 1Gi
  ingress:
    enabled: true
    #tls:
    #  enabled: true
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana      