kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: grafana-scc
  namespace: local-dev
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny  
users:
  - system:serviceaccount:local-dev:grafana-oauth-sa
  - system:serviceaccount:local-dev:grafana-operator-controller-manager