apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-proxy
  namespace: local-dev
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews", "subjectaccessreviews"]
    verbs: ["create"] 
