apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-grafana-ds
  namespace: local-dev
spec:
  datasources:
    - access: proxy
      editable: true
      secureJsonData:
        httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
      name: Prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      basicAuth: false
      isDefault: true
      version: 1
      type: prometheus
  instanceSelector:
    matchLabels:
      dashboards: grafana  
  name: prometheus-grafanadatasource.yaml


